steps:
  # 1. Build Docker image untuk backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/be202-tu7", "."]

  # 2. Push ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/be202-tu7"]

  # 3. Deploy ke Cloud Run dengan environment variables
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "be202-tu7",
        "--image",
        "gcr.io/$PROJECT_ID/be202-tu7",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--set-env-vars=DB_NAME=notes,DB_USERNAME=root,DB_PASSWORD=,DB_HOST=34.69.127.69,ACCESS_TOKEN_SECRET=inirahasia123,REFRESH_TOKEN_SECRET=refreshrahasia456"
      ]
# Log hanya akan disimpan di Google Cloud Logging
# Log tidak akan disimpan di Google Cloud Storage (butuh hak akses).
options:
  logging: CLOUD_LOGGING_ONLY
